openapi: 3.0.0
info:
  title: Microservicio de Cuentas Bancarias
  version: 1.0.0
  description: API para gestionar cuentas bancarias.

paths:
  /cuentas_bancarias/{accountId}:
    get:
      summary: Obtener información de una cuenta bancaria
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Información detallada de la cuenta bancaria.

    put:
      summary: Actualizar información de una cuenta bancaria
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BankAccount"
      responses:
        200:
          description: Información de la cuenta bancaria actualizada.

    delete:
      summary: Eliminar una cuenta bancaria
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Cuenta bancaria eliminada con éxito.

  /cuentas_bancarias:
    post:
      summary: Crear una nueva cuenta bancaria
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BankAccount"
      responses:
        201:
          description: Cuenta bancaria creada con éxito.


  /cuentas_bancarias/{accountId}/depositos:
    post:
      summary: Realizar un depósito en una cuenta bancaria
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DepositAmount"


      responses:
        200:
          description: Depósito realizado con éxito.

  /cuentas_bancarias/{accountId}/retiros:
    post:
      summary: Realizar un retiro desde una cuenta bancaria
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/WithdrawalAmount"
      responses:
        200:
          description: Retiro realizado con éxito.

  /cuentas_bancarias/{accountId}/movimientos:
    get:
      summary: Consultar movimientos de una cuenta bancaria
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Lista de movimientos de la cuenta bancaria.

components:
  schemas:
    BankAccount:
      type: object
      properties:
        accountId:
          type: string
        customerId:
          type: string
        accountType:
          type: string
        balance:
          type: string
        deposits:
          type: array
          items:
            $ref: "#/components/schemas/DepositAmount"
        withdrawalAmounts:
          type: array
          items:
            $ref: "#/components/schemas/WithdrawalAmount"

    DepositAmount:
      type: object
      properties:
        amount:
          type: number
        depositDate:
          type: string


    WithdrawalAmount:
      type: object
      properties:
        amount:
          type: number
        dateWithdrawal:
          type: string

